# Generated by Django 4.2.7 on 2026-02-13 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_image', models.ImageField(upload_to='food_images/')),
                ('food_name', models.CharField(max_length=200)),
                ('calories', models.FloatField()),
                ('carbs', models.FloatField(help_text='Carbohydrates (g)')),
                ('protein', models.FloatField(help_text='Protein (g)')),
                ('fat', models.FloatField(help_text='Fat (g)')),
                ('diabetes_suggestion', models.CharField(max_length=200)),
                ('fatty_liver_suggestion', models.CharField(max_length=200)),
                ('obesity_suggestion', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
